USE platzisocial;
GO
CREATE TABLE dbo.users
(
	id VARCHAR(32) NOT NULL DEFAULT '',
	username VARCHAR(32) NOT NULL DEFAULT '',
	name VARCHAR(64) NOT NULL DEFAULT '',
	CONSTRAINT PK_USERS_ID PRIMARY KEY CLUSTERED (id),
);
GO