USE platzisocial;
GO
CREATE TABLE dbo.auths
(
	id VARCHAR(32) NOT NULL DEFAULT '',
	username VARCHAR(32) NOT NULL DEFAULT '',
	password VARCHAR(64) NOT NULL DEFAULT '',
	CONSTRAINT PK_AUTHS_ID PRIMARY KEY CLUSTERED (id),
);
GO